package br.com.sixinf.webtracker.entidades;

// Generated Jan 9, 2014 12:27:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import br.com.sixinf.ferramentas.persistencia.Entidade;

/**
 * Conta generated by hbm2java
 */
@Entity
@Table(name = "conta", schema = "public")
public class Conta implements Entidade, Serializable {

	private static final long serialVersionUID = 1L;
		
	@Id
	@SequenceGenerator(name="seqConta", sequenceName="conta_id_seq")
	@GeneratedValue(strategy=GenerationType.IDENTITY, generator="seqConta")
	@Column(name="id")
	private Long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	private Usuario usuario;
	
	@Column(name = "mes")
	private Integer mes;
	
	@Column(name = "ano")
	private Integer ano;
	
	@Column(name = "saldo", precision = 131089, scale = 0)
	private BigDecimal saldo;
	
	@Column(name="status_registro")
	private Character statusRegistro;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conta", cascade=CascadeType.DETACH)
	private Set<Lancamento> lancamentos;

	public Conta() {
	}
	
	public Conta(Long id, Usuario usuario, Integer mes, Integer ano,
			BigDecimal saldo, Character statusRegistro,
			Set<Lancamento> lancamentos) {
		this.id = id;
		this.usuario = usuario;
		this.mes = mes;
		this.ano = ano;
		this.saldo = saldo;
		this.statusRegistro = statusRegistro;
		this.lancamentos = lancamentos;
	}
	
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	
	public Integer getAno() {
		return this.ano;
	}

	public void setAno(Integer ano) {
		this.ano = ano;
	}

	
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public Character getStatusRegistro() {
		return this.statusRegistro;
	}

	public void setStatusRegistro(Character statusRegistro) {
		this.statusRegistro = statusRegistro;
	}
	
	public Set<Lancamento> getLancamentos() {
		return this.lancamentos;
	}

	public void setLancamentos(Set<Lancamento> lancamentos) {
		this.lancamentos = lancamentos;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Override
	public Long getIdentificacao() {
		return id;
	}

}
