package br.com.sixinf.webtracker.entidades;

// Generated Jan 9, 2014 12:27:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pet generated by hbm2java
 */
@Entity
@PrimaryKeyJoinColumn(name="id")
@Table(name="pet")
public class Pet extends Tracker {
	
	private static final long serialVersionUID = 1L;
	
	@Column(name = "nome", length = 100)
	private String nome;
	
	@Column(name = "raca", length = 30)
	private String raca;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "data_nascimento", length = 13)
	private Date dataNascimento;
	
	public Pet() {
	}
	
	public Pet(String nome, String raca, Date dataNascimento) {
		this.nome = nome;
		this.raca = raca;
		this.dataNascimento = dataNascimento;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getRaca() {
		return this.raca;
	}

	public void setRaca(String raca) {
		this.raca = raca;
	}

	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

}
